name: GitHub Action Doxygen Jekyll

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout onnx-mlir source
      uses: actions/checkout@v2
      with:
        path: onnx-mlir

    - name: checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref:  gh-pages
        path: gh-pages

    - name: install doxygen and rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen rsync

    - name: copy docs into gh-pages
      run: |
        rsync -ahvP --delete $GITHUB_WORKSPACE/onnx-mlir/docs/ $GITHUB_WORKSPACE/gh-pages/

    - name: doxygen API html
      run: |
        ls -l $GITHUB_WORKSPACE/onnx-mlir
        ls -l $GITHUB_WORKSPACE/onnx-mlir/include
        mkdir -p $GITHUB_WORKSPACE/gh-pages/doxygen_html
        export INPUT=$GITHUB_WORKSPACE/onnx-mlir/include/OnnxMlirRuntime.h
        export HTML_OUTPUT=$GITHUB_WORKSPACE/gh-pages/doxygen_html/OnnxMlirRuntime
        echo $INPUT
        echo $HTML_OUTPUT
        doxygen $GITHUB_WORKSPACE/onnx-mlir/Doxyfile
        export INPUT=$GITHUB_WORKSPACE/onnx-mlir/include/onnx-mlir/Runtime/OMTensor.h
        export HTML_OUTPUT=$GITHUB_WORKSPACE/gh-pages/doxygen_html/OMTensor
        echo $INPUT
        echo $HTML_OUTPUT
        doxygen $GITHUB_WORKSPACE/onnx-mlir/Doxyfile
        export INPUT=$GITHUB_WORKSPACE/onnx-mlir/include/onnx-mlir/Runtime/OMTensorList.h
        export HTML_OUTPUT=$GITHUB_WORKSPACE/gh-pages/doxygen_html/OMTensorList
        echo $INPUT
        echo $HTML_OUTPUT
        doxygen $GITHUB_WORKSPACE/onnx-mlir/Doxyfile

    - name: commit updated gh-pages
      run: |
        cd $GITHUB_WORKSPACE/gh-pages
        git add .
        git commit -m "Updated by GitHub Action"
