name: GitHub Action Doxygen Jekyll

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout onnx-mlir source
      uses: actions/checkout@v2
      with:
        path: onnx-mlir

    - name: checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref:  gh-pages
        path: gh-pages

    - name: install doxygen and rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen rsync

    - name: copy docs into gh-pages
      run: |
        rsync -ahvP --delete --filter 'protect .*' \
              $GITHUB_WORKSPACE/onnx-mlir/docs/ $GITHUB_WORKSPACE/gh-pages/

    - name: doxygen API html
      run: |
        mkdir -p $GITHUB_WORKSPACE/gh-pages/doxygen_html

        (cat  $GITHUB_WORKSPACE/onnx-mlir/Doxyfile; \
         echo INPUT=$GITHUB_WORKSPACE/onnx-mlir/include/OnnxMlirRuntime.h; \
         echo HTML_OUTPUT=$GITHUB_WORKSPACE/gh-pages/doxygen_html/OnnxMlirRuntime) | \
        doxygen -

        (cat  $GITHUB_WORKSPACE/onnx-mlir/Doxyfile; \
         echo INPUT=$GITHUB_WORKSPACE/onnx-mlir/include/onnx-mlir/Runtime/OMTensor.h; \
         echo HTML_OUTPUT=$GITHUB_WORKSPACE/gh-pages/doxygen_html/OMTensor) | \
        doxygen -

        (cat  $GITHUB_WORKSPACE/onnx-mlir/Doxyfile; \
         echo INPUT=$GITHUB_WORKSPACE/onnx-mlir/include/onnx-mlir/Runtime/OMTensorList.h; \
         echo HTML_OUTPUT=$GITHUB_WORKSPACE/gh-pages/doxygen_html/OMTensorList) | \
        doxygen -

    - name: commit updated gh-pages
      run: |
        cd $GITHUB_WORKSPACE/gh-pages
        git config user.email "onnx-mlir@onnx.ai"
        git config user.name "onnx-mlir"
        git add .
        git commit -m "Updated by GitHub Action"
